# Generated by Django 2.2.2 on 2019-06-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('module', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_code', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
    ]
