# Generated by Django 2.2.2 on 2019-06-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190612_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_view',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('f_Email_id', models.EmailField(max_length=100)),
                ('f_phno', models.BigIntegerField()),
                ('f_chap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_days', models.BigIntegerField()),
                ('l_start_date', models.DateField(max_length=100)),
                ('l_end_date', models.DateField(max_length=100)),
                ('l_reason', models.CharField(max_length=100)),
                ('l_owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='chapters',
            old_name='module',
            new_name='m_id',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='chap',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='chapters',
            name='c_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='m_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters'),
        ),
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email_id',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='Usertype',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Faculty'), (3, 'Student')], default=3),
        ),
        migrations.CreateModel(
            name='Student_view',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
                ('s_Email_id', models.EmailField(max_length=100)),
                ('s_course', models.CharField(max_length=100)),
                ('s_chap', models.CharField(max_length=100)),
                ('c_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course')),
                ('f_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Faculty_view')),
                ('l_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Leave')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('se_id', models.AutoField(primary_key=True, serialize=False)),
                ('se_date', models.DateField(max_length=100)),
                ('se_detail', models.CharField(max_length=100)),
                ('se_owner', models.CharField(max_length=100)),
                ('c_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course')),
                ('m_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters')),
            ],
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='c_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='l_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Leave'),
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='m_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters'),
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='s_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Student_view'),
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='se_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Session'),
        ),
        migrations.CreateModel(
            name='Admin_view',
            fields=[
                ('A_id', models.AutoField(primary_key=True, serialize=False)),
                ('A_name', models.CharField(max_length=100)),
                ('A_phno', models.BigIntegerField()),
                ('A_Email_id', models.EmailField(max_length=100)),
                ('A_leave_accept', models.CharField(max_length=100, verbose_name='1')),
                ('A_leave_reject', models.CharField(max_length=100, verbose_name='0')),
                ('c_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course')),
                ('f_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Faculty_view')),
                ('l_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Leave')),
                ('m_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters')),
                ('s_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Student_view')),
                ('se_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Session')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='s_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Student_view'),
        ),
    ]
