# Generated by Django 2.2.2 on 2019-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190615_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_view',
            name='A_leave_accept',
        ),
        migrations.AddField(
            model_name='admin_view',
            name='A_leave',
            field=models.IntegerField(choices=[(0, 'Reject'), (1, 'Accept')], default=2),
        ),
    ]
