# Generated by Django 2.2.2 on 2019-06-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190615_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_view',
            name='A_leave_reject',
        ),
    ]
