# Generated by Django 2.2.2 on 2019-06-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_admin_view_a_leave_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Username',
        ),
    ]
