# Generated by Django 2.2.2 on 2019-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190621_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Usertype',
            field=models.IntegerField(max_length=100),
        ),
    ]
