# Generated by Django 2.2.2 on 2019-06-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190621_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='f_id',
        ),
    ]
