# Generated by Django 2.2.2 on 2019-06-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_remove_chapters_f_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='m_id',
        ),
        migrations.AddField(
            model_name='chapters',
            name='c_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
    ]
