# Generated by Django 2.2.2 on 2019-06-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20190621_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='c_code',
        ),
        migrations.AddField(
            model_name='course',
            name='m_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters'),
        ),
    ]
