# Generated by Django 2.2.2 on 2019-06-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20190621_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_view',
            name='A_leave_accept',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='A_leave_reject',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='c_code',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='f_id',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='l_id',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='admin_view',
            name='se_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='faculty_view',
            name='f_chap',
        ),
        migrations.RemoveField(
            model_name='student_view',
            name='s_chap',
        ),
        migrations.AddField(
            model_name='chapters',
            name='c_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
    ]
