# Generated by Django 2.2.2 on 2019-06-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20190626_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
