# Generated by Django 2.2.2 on 2019-06-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_delete_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_leave',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateField(max_length=100)),
                ('e_date', models.DateField(max_length=100)),
                ('l_reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student_leave',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('l_reason', models.CharField(max_length=500)),
            ],
        ),
    ]
