# Generated by Django 2.2.2 on 2019-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_faculty_leave_student_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_leave',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_leave',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='e_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='l_reason',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='s_date',
            field=models.DateField(max_length=100),
        ),
    ]
