# Generated by Django 2.2.2 on 2019-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20190627_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='c_code',
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_code', models.ForeignKey(default='', on_delete='models.CASCADE', to='schedule.Course')),
                ('m_id', models.ForeignKey(default='', on_delete='models.CASCADE', to='schedule.Chapters')),
            ],
        ),
    ]
