# Generated by Django 2.2.2 on 2019-06-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20190629_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_leave',
            old_name='name',
            new_name='s_f_name',
        ),
        migrations.RemoveField(
            model_name='faculty_leave',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faculty_view',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='student_view',
            name='s_name',
        ),
        migrations.AddField(
            model_name='faculty_leave',
            name='f_f_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty_leave',
            name='f_l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='f_f_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty_view',
            name='f_l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student_leave',
            name='s_l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student_view',
            name='s_f_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student_view',
            name='s_l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='c_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='m_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters'),
        ),
    ]
