# Generated by Django 2.2.2 on 2019-07-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20190630_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_leave',
            old_name='f_f_name',
            new_name='f_email',
        ),
        migrations.RenameField(
            model_name='student_leave',
            old_name='s_f_name',
            new_name='s_email',
        ),
        migrations.RemoveField(
            model_name='faculty_leave',
            name='f_l_name',
        ),
        migrations.RemoveField(
            model_name='student_leave',
            name='s_l_name',
        ),
    ]
