# Generated by Django 2.2.2 on 2019-07-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_accepted_faculty_leave_accepted_student_leave_module_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePM',
            fields=[
                ('PM_id', models.AutoField(primary_key=True, serialize=False)),
                ('Session_key', models.CharField(max_length=100)),
                ('Session_value', models.CharField(max_length=100)),
                ('m_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Chapters')),
            ],
        ),
        migrations.DeleteModel(
            name='Module_PM',
        ),
    ]
