# Generated by Django 2.2.2 on 2019-07-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_auto_20190706_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_leave',
            name='f_status',
        ),
        migrations.RemoveField(
            model_name='student_leave',
            name='s_status',
        ),
        migrations.AddField(
            model_name='faculty_leave',
            name='reject',
            field=models.CharField(default='', max_length=10, verbose_name='accept'),
        ),
        migrations.AddField(
            model_name='student_leave',
            name='reject',
            field=models.CharField(default='', max_length=10, verbose_name='accept'),
        ),
    ]
