# Generated by Django 2.2.2 on 2019-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_auto_20190707_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_leave',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='student_leave',
            name='reject',
        ),
        migrations.AddField(
            model_name='faculty_leave',
            name='f_status',
            field=models.CharField(default='', max_length=10, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='student_leave',
            name='s_status',
            field=models.CharField(default='', max_length=10, verbose_name='1'),
        ),
    ]
